### ISSUE TITLE
Windows issue

### ISSUE THREAD

**Issue by salarmehr** [hollodotme/Helpers#3]
Thanks for the wonderful code. 

This line of code cause exception on Windows 

      		$temp_dir = '/tmp' . DIRECTORY_SEPARATOR . 'PHPExport_' . rand( 1, 9999 );

I guess you should check  the current OS and use `%temp%` on windows.

**Comment by hollodotme** [comment]
Thank you for that issue, gonna fix this today in the evening.

**Comment by hollodotme** [comment]
Changed this line to use the `sys_get_temp_dir()` function which is OS-sensitive.
Tagged v0.2
