### ISSUE TITLE
"sudo nano /etc/modt in section 2.2

### ISSUE THREAD

**Issue by hoakzie** [hollodotme/Helpers#5]
There's a typo in section 2.2 that instructs to do:

$ sudo nano /etc/modt

Which will cause grief I guess when trying to see the motd file...

**Comment by hollodotme** [comment]
Sorry, I don't get it. What is wrong with opening / editing the /etc/motd file using nano in sudo?

**Comment by hollodotme** [comment]
I don't think this is actually an issue. Closing it.
