### ISSUE TITLE
How did you figure out the parameter for self-hosted-vagrant?

### ISSUE THREAD

**Issue by bibstha** [hollodotme/Helpers#8]
Hi,

I found your tutorial https://github.com/hollodotme/Helpers/blob/master/Tutorials/vagrant/self-hosted-vagrant-boxes-with-versioning.md very useful. I didn't find the information on vagrant docs. I am just curious where you found the instructions for how the json file is structured?

Thanks,

**Comment by hollodotme** [comment]
@bibstha Thank you! The basic info about the json catalog comes from here: https://www.vagrantup.com/docs/boxes/format.html
